export const reviews = [
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
    {
        name: "Jack",
        username: "@jack",
        body: "This is absolutely mind blowing. Animated UIs are the big leap forward on modern interfaces. Already thinking on how to build our website using these 💡",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1754176181497155584/_8KGb5fz_400x400.jpg",
      },
      {
        name: "Jill",
        username: "@jill",
        body: "I don't know what to say. I'm speechless. This is amazing.",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1878404975992426497/aEHTGU2F_400x400.jpg",
      },
      {
        name: "John",
        username: "@john",
        body: "I'm at a loss for words. This is amazing. I love it.",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1878404975992426497/aEHTGU2F_400x400.jpg",
      },
      {
        name: "Jack",
        username: "@jack",
        body: "I've never seen anything like this before. It's amazing. I love it.",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1878404975992426497/aEHTGU2F_400x400.jpg",
      },
      {
        name: "Jill",
        username: "@jill",
        body: "I don't know what to say. I'm speechless. This is amazing.",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1878404975992426497/aEHTGU2F_400x400.jpg",
      },
      {
        name: "John",
        username: "@john",
        body: "I'm at a loss for words. This is amazing. I love it.",
        link: "https://x.com/dezloperr",
        img: "https://pbs.twimg.com/profile_images/1878404975992426497/aEHTGU2F_400x400.jpg",
      }
]